export const fourChoicesStyles = {
  boxContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: "100%",
  },
  gridContainer: {
    display: "flex",
    width: "95%",
    height: "80vh",
    flexDirection: "row",
  },
  leftSideContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    marginTop: "10px",
    width: "100%",
  },
  ecuationContainer: {
    padding: "5px 10px",
    border: "3px solid #8eb6d8",
    fontSize: "1.7em",
    borderRadius: "5px",
    position: "relative",
    height: "5.5em",
    boxSizing: "border-box",
    fontFamily: "Times New Roman, Times, serif",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    animation: "back",
  },
  inputContainer: { margin: "0px", display: "flex", mt: 1 },
  rightSideContainer: {
    marginTop: "10px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    alignContent: "space-around",
    justifyContent: "space-around",
  },
  progressStyle: {
    display: "flex",
    color: "#fff",
  },
};
