export const mechanographyGameStyles = {
  boxContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: "100%",
  },
  gridContainer: {
    display: "flex",
    width: "95%",
    height: "80vh",
    flexDirection: "row",
  },
  leftSideContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    marginTop: "10px",
    width: "100%",
  },
  wordsArrayContainerFather: {
    fontSize: "2em",
    lineHeight: "2em",
    border: "1px solid #8eb6d8",
    overflow: "hidden",
    borderRadius: "5px",
    marginBottom: "10px",
    padding: "6px 12px 30px 12px",
    marginTop: "0px",
    position: "relative",
    height: "5em",
    boxSizing: "border-box",
    fontFamily: "Times New Roman, Times, serif",
  },
  wordsArrayContainerChild: {
    display: "flex",
    position: "relative",
    flexDirection: "row",
    color: "#1d4851",
    flexWrap: "wrap",
    padding: "0",
    margin: "0",
  },
  wordsArray: {
    padding: "3px 5px",
    borderRadius: "5px",
  },
  rightSideContainer: {
    marginTop: "10px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    alignContent: "center",
    justifyItems: "center",
    justifyContent: "space-around",
  },
  progressStyle: {
    display: "flex",
    color: "#fff",
  },
};
