export const roscoGameStyles = (_: number = 0, mode: string = "") => {
  return {
    boxContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      height: "100%",
      justifyContent: "flex-end",
    },
    leftSide: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-between",
    },
    anaswersAvatar: {
      display: "flex",
      alignContent: "center",
      justifyContent: "center",
      width: "50px",
      height: "50px",
      color: "white",
    },
    helpButtons: {
      display: "flex",
      flexDirection: "column-reverse",
      width: "100%",
      alignItems: "center",
      gap: 1,
    },
    rightSide: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      height: "100%",
      justifyContent: "space-between",
    },
    avatarLettersContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      gap: 1,
      flexWrap: "wrap",
      margin: 3,
    },
    avatarLetters: {
      display: "flex",
      alignContent: "center",
      justifyContent: "center",
      border: "solid 1px lightgrey",
      width: "50px",
      height: "50px",
    },
    startGameButton: {
      textAlign: "center",
      margin: "auto",
      display: "block",
      fontSize: "30px",
      width: "90%",
    },
    definition: {
      color: `${mode == "light" ? "black" : "white"}`,
    },
    formControlContainer: { width: "90%", display: "flex" },
    formControl: {
      marginBottom: 1,
      display: "flex",
      width: "100%",
      paddingRight: "25px",
    },
    textField: { margin: "auto", display: "block", width: "100%" },
    textFieldInputProps: {
      fontSize: "30px",
      letterSpacing: "3px",
      width: "100%",
    },
    checkAnswerButton: {
      height: "90% !important",
    },
    snackBar: {
      marginTop: "10vh",
      width: "100%",
      textAlign: "center",
      padding: "auto",
    },
    snackbarAlert: {
      "& .MuiAlert-message": { textAlign: "center", width: "inherit" },
    },
    resultsModal: {
      position: "absolute",
      bgcolor: "background.paper",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      width: "40%",
      p: 2,
      borderRadius: "15px",
    },
  };
};
