export const mathGameStyles = {
  boxContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: "100%",
  },
  gridContainer: {
    display: "flex",
    width: "95%",
    height: "80vh",
    flexDirection: "row",
  },
  leftSideContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    marginTop: "10px",
    width: "100%",
  },
  ecuationContainer: {
    fontSize: "2em",
    border: "3px solid #8eb6d8",
    borderRadius: "5px",
    position: "relative",
    height: "4em",
    boxSizing: "border-box",
    fontFamily: "Times New Roman, Times, serif",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    animation: "back",
  },
  inputContainer: { width: "100%", margin: "0px", display: "flex", gap: 2, mt: 2 },
  rightSideContainer: {
    marginTop: "10px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    alignContent: "center",
    justifyItems: "center",
    justifyContent: "space-around",
  },
  progressStyle: {
    display: "flex",
    color: "#fff",
  },
};
